# Generated by Django 3.2.12 on 2022-07-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_tur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='tek',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.tek', verbose_name='IMDB Puanı'),
        ),
    ]
